version: '3'

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}

volumes:
  mysql:
    driver: ${VOLUMES_DRIVER}
  redis:
    driver: ${VOLUMES_DRIVER}
  crontab:
    driver: ${VOLUMES_DRIVER}

services:
  nginx:
    build:
      context: ./nginx
      args:
        - PHP_UPSTREAM_CONTAINER=${NGINX_PHP_UPSTREAM_CONTAINER}
        - PHP_UPSTREAM_PORT=${NGINX_PHP_UPSTREAM_PORT}
    restart: always
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
    depends_on:
      - piplin-php
    networks:
      - frontend
      - backend

  piplin-php:
    build: ./piplin-php
    restart: always
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - ${CRONTAB_STORAGE}:/etc/cron.d
      - ${PIPLINPHP_SUPERVISORD_PATH}:/etc/supervisord.d
      - ${PIPLINPHP_LOG_PATH}:/var/log/supervisor
    expose:
      - "9000"
    depends_on:
      - mysql
      - redis
    networks:
      - backend

  mysql:
    build:
      context: ./mysql
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    restart: always
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TIMEZONE}
    volumes:
      - ${MYSQL_STORAGE}:/var/lib/mysql
    networks:
      - backend

  redis:
    build: ./redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ${REDIS_STORAGE}:/data
    networks:
      - backend
